
=== Core concepts

The central source of all configuration in Bootique DI is an instance of <<Injector>>.
It represents a registry that provides access to configured services.
Each injected service is called *binding* in terms of Bootique DI.
To create an `Injector` you need to provide a set of <<BQModule,configuration units>>
that define services available for injection.

Here is a simple example of Bootique DI usage:

[source,java,subs="verbatim,attributes"]
----
import javax.inject.Inject;

import io.bootique.di.DIBootstrap;
import io.bootique.di.Injector;

public class Application {
    public static void main(String[] args) {
        Injector injector = DIBootstrap
                .injectorBuilder(
                        binder -> binder.bind(Service.class)
                                    .to(MyService.class) // <!--1-->
                                    .inSingletonScope(),
                        binder -> binder.bind(Worker.class).to(MyWorker.class)
                )
                .build();
        Worker worker = injector.getInstance(Worker.class);
        worker.doWork();
    }
}

interface Worker {
    void doWork();
}

interface Service {
    String getInfo();
}

class MyService implements Service {

    @Override
    public String getInfo() {
        return "Hello world!";
    }
}

class MyWorker implements Worker {
    private Service service;

    @Inject
    MyWorker(Service service) {
        this.service = service;
    }

    public void doWork() {
        System.out.println(service.getInfo());
    }
}
----
<1> here we bind a `Service` interface to concrete implementation.

Each service known to `Injector` can be injected into field or constructor marked with `@javax.inject.Inject` annotation,
or into <<Custom factory methods,factory methods of modules>>. Optionally you can inject not only service itself but also
a lazy provider of that service. This can be very useful to break circular dependencies between services.
Here is an example of `Provider` injection:

[source,java]
----
class MyService implements Service {

    private Provider<Worker> workerProvider;

    @Inject
    MyService(Provider<Worker> workerProvider) {
        this.workerProvider = workerProvider;
    }

    // ...
}

class MyWorker implements Worker {
    private Service service;

    @Inject
    MyWorker(Service service) {
        this.service = service;
    }

    // ...
}
----
