
== Core concepts

The central source of all configuration in Bootique DI is an instance of <<Injector>>.
It represents a registry that provides access to configured services.
Each injected service is called *binding* in terms of Bootique DI.
To create an `Injector` you need to provide a set of <<BQModule,configuration units>>
that define services available for injection.

Here is a simple example of Bootique DI usage:

[source,java,indent=0,subs="verbatim,attributes"]
----
include::../../../../test/java/io/bootique/di/docs/bootiqueDI/core/Application.java[tags=Application]
----
<1> here we bind a `Service` interface to concrete implementation.

Each service known to `Injector` can be injected into field or constructor marked with `@javax.inject.Inject` annotation,
or into <<Custom factory methods,factory methods of modules>>. Optionally you can inject not only service itself but also
a lazy provider of that service. This can be very useful to break circular dependencies between services.
Here is an example of `Provider` injection:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/bootiqueDI/core/Application.java[tags=Provider]
----
