
== Binder

Binder provides the API for the module to bind its services to the DI container.
Every binding is defined by its key. In a simple case, binding key based on just a java class.

=== Service binding

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind1]
----

NOTE: using interface is optional, you can directly bind implementation: `binder.bind(MyService.class);`

In this case, `MyService` will be created by the container. As an alternative,
you can provide a manually initialized instance of the `MyService`.

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind2]
----

Or you can use a custom factory for that:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind3]
----

Note that `MyServiceProvider` can use injection like any other service managed
by the DI container:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=ServiceProvider]
----

Moreover, `MyServiceProvider` can be configured as a binding itself:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind4]
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind5]
----

The final option of how you can bind service is via a concrete `Provider` implementation:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind6]
----

=== Qualifiers

Sometimes, it's required to provide several variants of the same service.
In that case, you need to distinguish them at the injection point.
For that you can use qualifiers. A simple qualifier is a service name:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind7]
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind8]
----

To inject this service you need to use `javax.inject.Named` annotation at the injection point:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyWorker.java[tags=MyWorker]
----

Additionally, you can use custom annotation to achieve this:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/Marker.java[tags=Marker]
----

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyServiceProvider.java[tags=Bind9]
----

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/MyWorker.java[tags=MyWorker2]
----

=== Generics

Due to generics implementation in Java, you can't directly use something like `Service<String>.class` to bind generic classes.
For these cases, Bootique DI provides helper class `TypeLiteral`.

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/generics/Generics.java[tags=Bind]
----

NOTE: you don't need additional qualifiers to inject different versions of the generic class.

=== Collections

Collections can be injected like any other generic class mentioned above. However, there is advanced support for `Set`
and `Map` injection offered by Binder API.

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/collections/MyModule.java[tags=MyModule]
----

=== Optional binding

In normal cases, Bootique DI will throw an exception if injected service is missing.
If you want to make some service optional you can create an optional binding for it.

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/di/docs/binder/optional/MyModule.java[tags=MyModule]
----
